Add all files
susiku/Hello-World pull request #1
Opened 2022-03-22 21:19 UTC by susiku

linter-error-flag

2022-03-22 22:34 UTC, Lordkaito requested changes
Hi @susiku, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 22:34 UTC, Lordkaito commented on test.md
> +this will be ignored by git
- [ ] Please make sure that this file is ignored by git, as this is not supposed to be in your repository.

2022-03-23 14:20 UTC, gemmen29 approved these changes
Hi @susiku, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 14:20 UTC, gemmen29 commented on README.md
> +
[OPTIONAL] Kindly remove this section as there is no live demo, you add this only if there exists a live demo for the project.

2022-03-23 14:20 UTC, gemmen29 commented on README.md
> +
[OPTIONAL] Kindly remove this section, you add this only if there exists a `Prerequisites`, `Setup`, `Install`, `Usage`, `Run tests`, `Deployment` for the project.

2022-03-23 14:20 UTC, gemmen29 commented on README.md
> +👤
[OPTIONAL] Kindly remove this icon. as there is only one author in that project.

2022-03-23 14:42 UTC, merged